version: '3.3'

services:
  app:
    build:
      context: .
      args:
        - DEV=ture
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    